from werkzeug.security import generate_password_hash, check_password_hash
from . import db


class User(db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, autoincrement=True, primary_key=True)
    username = db.Column(db.String(64), nullable=False, unique=True, index=True)
    password_hash = db.Column(db.String(128), nullable=False)
    email = db.Column(db.String(64), unique=True, index=True)
    telephone = db.Column(db.String(12))
    create_time = db.Column(db.DateTime)
    last_login_time = db.Column(db.DateTime)
    user_desc = db.Column(db.Text)
    city = db.Column(db.String(64))
    address = db.Column(db.Text)
    flag = db.Column(db.String)

    @property
    def password(self):
        raise AttributeError('password 不是一个可读属性')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)


class NoCoImage(db.Model):
    __tablename__ = 'no_co_images'
    id = db.Column(db.Integer, autoincrement=True, primary_key=True)
    image_name = db.Column(db.String(64), nullable=False)
    image_num = db.Column(db.String(64))
    power_company_province = db.Column(db.String(64))
    power_company_cityorcountry = db.Column(db.String(64))
    suborlineorzone_name = db.Column(db.String(64))
    location_detail = db.Column(db.Text)
    location_nature = db.Column(db.String(10))
    original_image_path = db.Column(db.Text)
    ccd_image_path = db.Column(db.Text)
    matrix_path = db.Column(db.Text)
    production_date = db.Column(db.Date)
    run_date = db.Column(db.Date)
    detection_date = db.Column(db.Date)
    detection_time = db.Column(db.Time)
    report_date = db.Column(db.Date)
    instrument_model = db.Column(db.String(20))
    instrument_num = db.Column(db.String(20))
    reporter = db.Column(db.String(20))
    steward = db.Column(db.String(20))
    inspector = db.Column(db.String(20))
    reviewer = db.Column(db.String(20))
    auditor = db.Column(db.String(20))
    rated_current = db.Column(db.Float)
    load_current = db.Column(db.Float)
    voltage_level = db.Column(db.Float)
    weather = db.Column(db.String(20))
    emissivity = db.Column(db.Float)
    wind_speed = db.Column(db.Float)
    test_distance = db.Column(db.Float)
    max_temp = db.Column(db.Float)
    min_temp = db.Column(db.Float)
    env_temp = db.Column(db.Float)
    env_humi = db.Column(db.Float)
    device_name = db.Column(db.String(50))
    device_type = db.Column(db.String(20))
    interval_name = db.Column(db.String(50))
    test_unit = db.Column(db.String(50))
    test_nature = db.Column(db.String(20))


class CoImage(db.Model):
    __tablename__ = 'co_images'
    id = db.Column(db.Integer, autoincrement=True, primary_key=True)
    image_name = db.Column(db.String(64), nullable=False)
    image_num = db.Column(db.String(64))
    power_company_province = db.Column(db.String(64))
    power_company_cityorcountry = db.Column(db.String(64))
    suborlineorzone_name = db.Column(db.String(64))
    location_detail = db.Column(db.Text)
    location_nature = db.Column(db.String(10))
    original_image_path = db.Column(db.Text)
    clean_image_path = db.Column(db.Text)
    diagnose_image_path = db.Column(db.Text)
    ccd_image_path = db.Column(db.Text)
    matrix_path = db.Column(db.Text)
    production_date = db.Column(db.Date)
    run_date = db.Column(db.Date)
    detection_date = db.Column(db.Date)
    detection_time = db.Column(db.Time)
    report_date = db.Column(db.Date)
    instrument_model = db.Column(db.String(20))
    instrument_num = db.Column(db.String(20))
    reporter = db.Column(db.String(20))
    steward = db.Column(db.String(20))
    inspector = db.Column(db.String(20))
    reviewer = db.Column(db.String(20))
    auditor = db.Column(db.String(20))
    rated_current = db.Column(db.Float)
    load_current = db.Column(db.Float)
    voltage_level = db.Column(db.Float)
    weather = db.Column(db.String(20))
    emissivity = db.Column(db.Float)
    wind_speed = db.Column(db.Float)
    test_distance = db.Column(db.Float)
    max_temp = db.Column(db.Float)
    min_temp = db.Column(db.Float)
    env_temp = db.Column(db.Float)
    env_humi = db.Column(db.Float)
    device_name = db.Column(db.String(50))
    device_type = db.Column(db.String(20))
    interval_name = db.Column(db.String(50))
    test_unit = db.Column(db.String(50))
    test_nature = db.Column(db.String(20))
    defect_part = db.Column(db.String(50))
    defect_type = db.Column(db.String(20))
    trouble_rank = db.Column(db.String(20))
    diagnose_analyse = db.Column(db.Text)
    processing_way = db.Column(db.Text)
    rrg_temp = db.Column(db.Float)
    hot_mode = db.Column(db.String(20))
    r1_name = db.Column(db.String(50))
    r2_name = db.Column(db.String(50))
    r3_name = db.Column(db.String(50))
    r4_name = db.Column(db.String(50))
    r5_name = db.Column(db.String(50))
    phase1_name = db.Column(db.String(10))
    phase2_name = db.Column(db.String(10))
    phase3_name = db.Column(db.String(10))
    phase4_name = db.Column(db.String(10))
    phase5_name = db.Column(db.String(10))
    max_tm1 = db.Column(db.Float)
    max_tm2 = db.Column(db.Float)
    max_tm3 = db.Column(db.Float)
    max_tm4 = db.Column(db.Float)
    max_tm5 = db.Column(db.Float)
    min_tm1 = db.Column(db.Float)
    min_tm2 = db.Column(db.Float)
    min_tm3 = db.Column(db.Float)
    min_tm4 = db.Column(db.Float)
    min_tm5 = db.Column(db.Float)
    avg_tm1 = db.Column(db.Float)
    avg_tm2 = db.Column(db.Float)
    avg_tm3 = db.Column(db.Float)
    avg_tm4 = db.Column(db.Float)
    avg_tm5 = db.Column(db.Float)
    rtd = db.Column(db.Float)
    td = db.Column(db.Float)
